# Generated by Django 6.0.4 on 2026-04-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('owner', 'Owner'), ('admin', 'Admin')], default='renter', max_length=10),
        ),
    ]
