# Generated by Django 6.0.4 on 2026-04-18 15:18

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_kyc_video_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kyc_video',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='gearshare-kyc-private', file_overwrite=False, querystring_auth=True, querystring_expire=3600), upload_to='kyc_videos/'),
        ),
    ]
