# Generated by Django 6.0.4 on 2026-04-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_kyc_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspension_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
