# Generated by Django 6.0.4 on 2026-04-23 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_kyc_attempts_customuser_suspension_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('Like New', 'Like New'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair')], default='Good', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gear_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
