# Generated by Django 6.0.4 on 2026-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_gearitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='price_period',
            field=models.CharField(default='Day', max_length=20),
        ),
    ]
