# Generated by Django 6.0.4 on 2026-05-01 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_gearitem_price_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_switch_role',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoleSwitchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(max_length=10)),
                ('requested_role', models.CharField(max_length=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='role_request_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_switch_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
