# Generated by Django 6.0.4 on 2026-05-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_can_switch_role_roleswitchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_status_msg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
