# Generated by Django 6.0.4 on 2026-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_role_status_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='min_trust_tier',
            field=models.IntegerField(default=1),
        ),
    ]
