# Generated by Django 6.0.4 on 2026-05-04 17:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_gearitem_min_trust_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='available_days',
            field=models.CharField(default='S,M,T,W,Th,F,Sa', max_length=100),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='cancellation_policy',
            field=models.CharField(default='flexible', max_length=50),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='delivery_option',
            field=models.CharField(default='Pickup only', max_length=50),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='min_rental_duration',
            field=models.CharField(default='1 day', max_length=50),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='replacement_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gearitem',
            name='min_trust_tier',
            field=models.IntegerField(default=7),
        ),
    ]