# Generated by Django 6.0.4 on 2026-05-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_transaction_count_gearitem_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GearImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gear_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='users.gearitem')),
            ],
        ),
    ]
