# Generated by Django 6.0.4 on 2026-05-05 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_transaction_count_gearitem_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GearGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gear_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='users.gearitem')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='users.gearitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_received', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
