# Generated by Django 6.0.4 on 2026-05-10 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_transaction_count_gearitem_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='is_negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='GearGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gear_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='users.gearitem')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('negotiated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='users.gearitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_received', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_system_update', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.rentalrequest')),
            ],
        ),
    ]
