# Generated by Django 6.0.4 on 2026-05-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_transaction_count_gearitem_is_negotiable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
