# Generated by Django 6.0.4 on 2026-05-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_gearitem_area_gearitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearitem',
            name='min_trust_tier',
            field=models.IntegerField(default=1),
        ),
    ]
