# Generated by Django 6.0.4 on 2026-05-16 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_auth_provider_customuser_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='evidence_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='renter_agreed_price',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RentalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence_vault/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_photos', to='users.rentalrequest')),
            ],
        ),
    ]
