# Generated by Django 6.0.4 on 2026-05-16 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rentalrequest_evidence_uploaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rental_completed', 'Rental Completed'), ('positive_review', 'Positive Review (4–5★)'), ('on_time_return', 'On-Time Return'), ('kyc_verified', 'KYC Verified'), ('late_return', 'Late Return (per day)'), ('last_min_cancel', 'Last-Minute Cancellation'), ('poor_review', 'Poor Review (1–2★)'), ('dispute_lost_minor', 'Dispute Lost (minor)'), ('dispute_lost_major', 'Dispute Lost (major)'), ('inactivity_decay', 'Inactivity Decay'), ('admin_adjustment', 'Admin Manual Adjustment')], max_length=40)),
                ('delta', models.FloatField()),
                ('score_before', models.FloatField()),
                ('score_after', models.FloatField()),
                ('tier_before', models.CharField(max_length=20)),
                ('tier_after', models.CharField(max_length=20)),
                ('rental_request_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_score_user_id_3f3f35_idx')],
            },
        ),
    ]
