"""
Django settings for gearshare_core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#=22o^znjjf8u94j@xbbl8mhl-lj+e!fplu3vkxgdzv3t*&+!l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gearshare_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gearshare_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.kyjuuqtxpjsiyodgnjfp',
        'PASSWORD': 'Crazy_Phantom@#$',  # <-- PUT YOUR REAL PASSWORD HERE
        'HOST': 'aws-1-ap-southeast-1.pooler.supabase.com',
        'PORT': '6543',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# This tells Django where to look for static files outside of standard apps
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

AUTH_USER_MODEL = 'users.CustomUser'


# --- SUPABASE S3 CLOUD STORAGE CONFIGURATION ---
AWS_ACCESS_KEY_ID = '1a1a9d6f744bdcf34eee96978c3afbfe'
AWS_SECRET_ACCESS_KEY = 'cf8247ff2bed8d775c03cf727a2c3a26a4d61fc38401f9518022e9049e3670f7'
AWS_S3_ENDPOINT_URL = 'https://kyjuuqtxpjsiyodgnjfp.storage.supabase.co/storage/v1/s3'
AWS_S3_REGION_NAME = 'ap-southeast-1'
AWS_S3_ADDRESSING_STYLE = "path"

# NEW: Supabase strictly requires Signature Version 4 for Private Presigned URLs
AWS_S3_SIGNATURE_VERSION = "s3v4"

# THE DUAL-BRAIN STORAGE ROUTER (DJANGO 6.0+)
STORAGES = {
    # Brain 1: The Public CDN (For Profile Pictures)
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": "gearshare-media",
            "custom_domain": "kyjuuqtxpjsiyodgnjfp.supabase.co/storage/v1/object/public/gearshare-media",
            "querystring_auth": False,
            "file_overwrite": False,
        }
    },

    # Brain 2: The Private Vault (For KYC Videos)
    "private_kyc": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": "gearshare-kyc-private",
            "custom_domain": None,       # <--- CRITICAL FIX: Stops the public CDN from hijacking this private URL
            "querystring_auth": True,
            "querystring_expire": 3600,  # URL stays alive for 1 hour to prevent timezone drift
            "file_overwrite": False,
        }
    },

    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}